Update README for ACL
waratuman/standardapi pull request #55
Opened 2021-11-10 20:59 UTC by malomalo

2021-11-10 21:03 UTC, bemky approved these changes

2021-11-15 14:09 UTC, waratuman requested changes

2021-11-15 14:09 UTC, waratuman commented on README.md
> +      including StandardAPI
```suggestion
      include StandardAPI
```

2022-01-11 22:04 UTC, malomalo commented
Push this out?

2022-01-11 22:09 UTC, waratuman commented
👍🏼

On Tue, Jan 11, 2022 at 17:05 Jon Bracy ***@***.***> wrote:

> Push this out?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/waratuman/standardapi/pull/55#issuecomment-1010399690>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAEOM35KG25GCSYN2PPLBLUVSSRNANCNFSM5HY4NIUQ>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-01-11 22:39 UTC, merged