New destroy options
waratuman/standardapi pull request #77
Opened 2023-12-04 18:22 UTC by bjbatten

What currently happens now is an array of ids is supplied, it is converted to a slash separated string:

"84/85" etc.

wrap in a transaction to ensure rollback behavior.

Test  that array of ids, or comma separated string is supported

2023-12-04 20:20 UTC, malomalo reviewed
Why split on `/` I feel like that should be kept as the separator for the url no?

2023-12-05 17:21 UTC, malomalo commented on lib/standard_api/controller.rb
> +      end
```suggestion
      if params[:id].include?(',')
        ActiveRecord::Base.transaction do
          # Would love to do this, but now sure destroy_all! is in Rails;
          # and perhaps it should be...
          resources.where(id: params[:id].split(',')).destroy_all!
          
          # So we will do this, using find will Rails
          # `ActiveRecord::RecordNotFound` which I think is what we
          # want but not sure so better safe than sorry:
          resources.find(id: params[:id].split(',')).each(&:destroy!)
        end
      else
        # Skips opening the transaction for just one destroy
        resources.find(params[:id]).destroy!
      end
```

2023-12-05 17:55 UTC, bjbatten commented on lib/standard_api/controller.rb
> +      end
`resources.find` didn't work, but `resources.where` did

2023-12-05 20:41 UTC, bjbatten commented
![image](https://github.com/waratuman/standardapi/assets/2322167/d9841b19-a4bb-45ae-9baf-494cc3a0dd45)

2023-12-05 20:54 UTC, malomalo commented on lib/standard_api/controller.rb
> +
```suggestion
      resources = resources.find(params[:id].split(','))
      ActiveRecord::Base.transaction { resources.each(&:destroy!) }
```

2023-12-05 20:55 UTC, malomalo commented on lib/standard_api/controller.rb
> +
This will only open a transaction after if find them, the find could fail and raise a not found error and not need the transaction at all

2023-12-06 03:28 UTC, waratuman requested changes

2023-12-06 03:28 UTC, waratuman commented on lib/standard_api/controller.rb
> +      ActiveRecord::Base.transaction { records.each(&:destroy!) }
Shouldn't this be called on the model class? The `ActiveRecord::Base` may not be the same connection that the model is using. See https://guides.rubyonrails.org/active_record_multiple_databases.html

2023-12-06 03:52 UTC, merged